imports:
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/state_machine/mollie_subscription.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/state_machine/checkout.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/state_machine/mollie_subscription_manual.yaml" }
