winzou_state_machine:
    bitbag_mollie_subscription_manual:
        class: "%bitbag_sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: state
        graph: mollie_subscription_payment_graph_manual
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            active: ~
            processing: ~
            paused: ~
            canceled: ~
            completed: ~

        transitions:
            pause:
                from: [ active ]
                to: paused
            resume:
                from: [ paused ]
                to: active
            cancel:
                from: [ new, active, processing ]
                to: canceled
