winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_process_subscription_fail:
                    on: [ "fail" ]
                    do: [ "@bitbag_sylius_mollie_plugin.payment_processing.subscription_payment_processor", "processFailed" ]
                    args: [ "object" ]

                sylius_process_subscription_success:
                    on: [ "complete" ]
                    do: [ "@bitbag_sylius_mollie_plugin.payment_processing.subscription_payment_processor", "processSuccess" ]
                    args: [ "object" ]

    bitbag_mollie_subscription_manual:
        class: "%bitbag_sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: state
        graph: mollie_subscription_payment_graph_manual
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            active: ~
            processing: ~
            paused: ~
            canceled: ~
            completed: ~

        transitions:
            pause:
                from: [ active ]
                to: paused
            resume:
                from: [ paused ]
                to: active
            cancel:
                from: [ active, processing ]
                to: canceled
        callbacks: ~

    mollie_subscription_payment_state_graph:
        class: "%bitbag_sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: paymentState
        graph: mollie_subscription_payment_state_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            pending: ~
            ok: ~
            fail: ~
        transitions:
            begin:
                from: [ ok, fail ]
                to: pending
            success:
                from: [ pending ]
                to: ok
            failure:
                from: [ pending ]
                to: ok
